on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      tags:
        description: 'Test scenario tags'
        required: false 
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
      postUrl:
        description: 'Link to article'
        required: true
        type: string
      postComment:
        description: 'Comment on article'
        required: false
        type: string
jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
        env:
          LEVEL: ${{ github.event.inputs.logLevel }}
          TAGS: ${{ github.event.inputs.tags }}
          ENVIRONMENT: ${{ github.event.inputs.environment }}
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}
      - name: Create report file
        run: echo "$POST_URL" > index.html
        env:
          POST_URL: ${{ github.event.inputs.postUrl }}
          POST_COMMENT: ${{ github.event.inputs.postComment }}
      - name: Commit report
        run: |
          git config --global user.name 'freko247'
          git config --global user.email 'freko247@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Automated publish"
          git push
