on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      tags:
        description: 'Test scenario tags'
        required: false 
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
      postUrl:
        description: 'Link to article'
        required: true
        type: string
      postComment:
        description: 'Comment on article'
        required: false
        type: string
jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
        env:
          LEVEL: ${{ github.event.inputs.logLevel }}
          TAGS: ${{ github.event.inputs.tags }}
          ENVIRONMENT: ${{ github.event.inputs.environment }}
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Create/update todays blog
        run: |
          now=$(date +"%m_%d_%Y")
          echo "$POST_URL" >> blog_${now}.html
        env:
          POST_URL: ${{ github.event.inputs.postUrl }}
          POST_COMMENT: ${{ github.event.inputs.postComment }}
      - name: Rebuild index page
        run: |
          # Generate list of files\
          ls
          # Delete and Generate index.html
          rm index.html
          now=$(date +"%m_%d_%Y")
          cp "blog_${now}.html" index.html
      - name: Commit report
        run: |
          git config --global user.name 'freko247'
          git config --global user.email 'freko247@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/${{ github.repository }}
          now=$(date +"%Y_%m_%d")
          git add "blog_${now}.html"
          git commit -am "Automated publish"
          git push
